Items quantity- add increment/decrement btn and functionality
vaantheman/restaurang-grupp-2 pull request #12
Opened 2023-12-19 17:48 UTC by vaantheman

2023-12-19 20:38 UTC, Moosees requested changes
addToLocalStorage should not save duplicates and that removes the need to filter duplicates when reading items in cartItemsDisplay

2023-12-19 20:42 UTC, Moosees commented
disabling addToCardButtons doesn't seem to work, and I don't see why they should be disabled

2023-12-19 20:44 UTC, KaptenSven approved these changes

2023-12-19 22:25 UTC, nyusufdot88 approved these changes

2023-12-20 03:23 UTC, Moosees approved these changes

2023-12-20 03:23 UTC, merged